"""PDF export for lesson plans.

Generates clean PDF documents via reportlab.
"""

from __future__ import annotations

from datetime import date
from pathlib import Path
from typing import TYPE_CHECKING

from clawed.export_theme import _resolve_output

if TYPE_CHECKING:
    from clawed.models import DailyLesson, TeacherPersona


def _esc(text: str) -> str:
    """Escape text for reportlab XML-based Paragraphs."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def export_lesson_pdf(
    lesson: "DailyLesson",
    persona: "TeacherPersona",
    output_dir: Path | None = None,
) -> Path:
    """Generate a PDF from a lesson plan via reportlab.

    Returns the path to the saved .pdf file.
    """
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import inch
    from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer

    out = _resolve_output(output_dir, lesson, ".pdf")

    doc = SimpleDocTemplate(
        str(out),
        pagesize=letter,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
        leftMargin=1 * inch,
        rightMargin=1 * inch,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "LessonTitle",
        parent=styles["Title"],
        fontSize=20,
        spaceAfter=6,
    )
    heading_style = ParagraphStyle(
        "SectionHeading",
        parent=styles["Heading2"],
        fontSize=14,
        spaceBefore=12,
        spaceAfter=4,
    )
    body_style = ParagraphStyle(
        "Body",
        parent=styles["Normal"],
        fontSize=11,
        leading=15,
        spaceAfter=6,
    )
    meta_style = ParagraphStyle(
        "Meta",
        parent=styles["Normal"],
        fontSize=9,
        textColor="#555555",
        spaceAfter=12,
    )

    story = []

    # Title
    story.append(Paragraph(_esc(lesson.title), title_style))
    story.append(
        Paragraph(
            _esc(
                f"Teacher: {persona.name or 'Teacher'}  |  "
                f"Lesson {lesson.lesson_number}  |  "
                f"{date.today().strftime('%B %d, %Y')}"
            ),
            meta_style,
        )
    )

    # Objective
    story.append(Paragraph("Objective (SWBAT)", heading_style))
    story.append(Paragraph(_esc(lesson.objective), body_style))

    # Standards
    if lesson.standards:
        story.append(Paragraph("Standards", heading_style))
        for s in lesson.standards:
            story.append(Paragraph(f"- {_esc(s)}", body_style))

    # Sections
    sections = [
        ("Do Now / Warm-Up", lesson.do_now),
        ("Direct Instruction", lesson.direct_instruction),
        ("Guided Practice", lesson.guided_practice),
        ("Independent Work", lesson.independent_work),
    ]
    for heading, content in sections:
        if content:
            story.append(Paragraph(_esc(heading), heading_style))
            story.append(Paragraph(_esc(content), body_style))

    # Exit Ticket
    if lesson.exit_ticket:
        story.append(Paragraph("Exit Ticket", heading_style))
        for i, q in enumerate(lesson.exit_ticket, 1):
            story.append(Paragraph(f"{i}. {_esc(q.question)}", body_style))

    # Homework
    if lesson.homework:
        story.append(Paragraph("Homework", heading_style))
        story.append(Paragraph(_esc(lesson.homework), body_style))

    # Footer
    story.append(Spacer(1, 24))
    footer_style = ParagraphStyle(
        "Footer", parent=styles["Normal"], fontSize=8, textColor="#888888"
    )
    story.append(Paragraph("Generated by EDUagent", footer_style))

    doc.build(story)
    return out
