"""LLM-generated student handout export.

Unlike export_docx.export_student_handout() which regex-parses the lesson plan,
this module takes structured handout data generated by a separate LLM call.
The handout is a first-class output, not a reformatted lesson plan.
"""
from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


def export_handout_docx(
    handout_data: dict[str, Any],
    subject: str = "",
    output_dir: Path | None = None,
) -> Path:
    """Export an LLM-generated student handout to DOCX."""
    from docx import Document
    from docx.enum.table import WD_TABLE_ALIGNMENT
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.shared import Inches, Pt, RGBColor

    from clawed.export_theme import get_color_theme
    from clawed.sanitize import sanitize_text

    theme = get_color_theme(subject)
    primary_rgb = RGBColor(
        int(theme["primary"][:2], 16),
        int(theme["primary"][2:4], 16),
        int(theme["primary"][4:6], 16),
    )

    doc = Document()

    # Page setup
    for section in doc.sections:
        section.top_margin = Inches(0.6)
        section.bottom_margin = Inches(0.5)
        section.left_margin = Inches(0.75)
        section.right_margin = Inches(0.75)

    # Default font
    style = doc.styles["Normal"]
    style.font.name = "Calibri"
    style.font.size = Pt(11)

    title = sanitize_text(handout_data.get("title", "Student Handout"))

    # Header
    title_para = doc.add_paragraph()
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title_para.add_run(title)
    run.bold = True
    run.font.size = Pt(16)
    run.font.color.rgb = primary_rgb

    # Name/Date/Period line
    meta = doc.add_paragraph()
    meta.alignment = WD_ALIGN_PARAGRAPH.LEFT
    meta_run = meta.add_run("Name: _____________________   Date: ____________   Period: ______")
    meta_run.font.size = Pt(10)

    def _section_heading(text):
        para = doc.add_paragraph()
        para.paragraph_format.space_before = Pt(12)
        para.paragraph_format.space_after = Pt(4)
        r = para.add_run(text)
        r.bold = True
        r.font.size = Pt(13)
        r.font.color.rgb = primary_rgb

    def _add_lines(count=3):
        for _ in range(count):
            p = doc.add_paragraph("")
            p.paragraph_format.space_after = Pt(10)
            # Bottom border for writing line
            from docx.oxml.ns import qn

            pPr = p._p.get_or_add_pPr()
            pBdr = pPr.makeelement(qn("w:pBdr"), {})
            bottom = pBdr.makeelement(
                qn("w:bottom"),
                {
                    qn("w:val"): "single",
                    qn("w:sz"): "4",
                    qn("w:space"): "1",
                    qn("w:color"): "CCCCCC",
                },
            )
            pBdr.append(bottom)
            pPr.append(pBdr)

    # Do Now
    do_now = handout_data.get("do_now", "")
    if do_now:
        _section_heading("Do Now")
        doc.add_paragraph(sanitize_text(do_now))
        _add_lines(4)

    # Vocabulary
    vocab = handout_data.get("vocabulary", [])
    if vocab:
        _section_heading("Key Vocabulary")
        for item in vocab:
            term = sanitize_text(item.get("term", ""))
            defn = sanitize_text(item.get("definition", ""))
            p = doc.add_paragraph()
            r = p.add_run(f"{term}")
            r.bold = True
            r.font.size = Pt(11)
            p.add_run(f" --- {defn}")

    # Source Excerpts
    sources = handout_data.get("source_excerpts", [])
    if sources:
        _section_heading("Primary Source Excerpts")
        for src in sources:
            text = sanitize_text(src.get("text", ""))
            attrib = sanitize_text(src.get("attribution", ""))
            # Indented quote
            p = doc.add_paragraph()
            p.paragraph_format.left_indent = Inches(0.5)
            r = p.add_run(f'"{text}"')
            r.italic = True
            r.font.size = Pt(11)
            if attrib:
                a = doc.add_paragraph()
                a.paragraph_format.left_indent = Inches(0.5)
                ar = a.add_run(f"--- {attrib}")
                ar.font.size = Pt(9)
                ar.font.color.rgb = RGBColor(0x66, 0x66, 0x66)

    # Graphic Organizer
    organizer = handout_data.get("organizer")
    if organizer and organizer.get("columns"):
        _section_heading(sanitize_text(organizer.get("title", "Graphic Organizer")))
        instructions = organizer.get("instructions", "")
        if instructions:
            doc.add_paragraph(sanitize_text(instructions))

        columns = organizer["columns"]
        num_rows = organizer.get("num_rows", 4)
        table = doc.add_table(rows=num_rows + 1, cols=len(columns))
        table.alignment = WD_TABLE_ALIGNMENT.CENTER

        # Header row
        for i, col in enumerate(columns):
            cell = table.rows[0].cells[i]
            cell.text = sanitize_text(col)
            for p in cell.paragraphs:
                for r in p.runs:
                    r.bold = True
                    r.font.size = Pt(10)

        # Style the table borders
        from docx.oxml.ns import qn

        tbl = table._tbl
        tblPr = tbl.tblPr if tbl.tblPr is not None else tbl.makeelement(qn("w:tblPr"), {})
        borders = tblPr.makeelement(qn("w:tblBorders"), {})
        for edge in ("top", "left", "bottom", "right", "insideH", "insideV"):
            el = borders.makeelement(
                qn(f"w:{edge}"),
                {
                    qn("w:val"): "single",
                    qn("w:sz"): "6",
                    qn("w:space"): "0",
                    qn("w:color"): "444444",
                },
            )
            borders.append(el)
        tblPr.append(borders)

    # Activity Instructions
    activity = handout_data.get("activity_instructions", "")
    if activity:
        _section_heading("Activity")
        doc.add_paragraph(sanitize_text(activity))
        _add_lines(3)

    # Exit Ticket
    questions = handout_data.get("exit_ticket_questions", [])
    if questions:
        _section_heading("Exit Ticket")
        for i, q in enumerate(questions, 1):
            p = doc.add_paragraph()
            r = p.add_run(f"{i}. {sanitize_text(q)}")
            r.font.size = Pt(11)
            _add_lines(3)

    # Image descriptions (visual cues for the teacher)
    img_descs = handout_data.get("image_descriptions", [])
    if img_descs:
        _section_heading("Visual Materials")
        for desc in img_descs:
            description = sanitize_text(desc.get("description", ""))
            context = sanitize_text(desc.get("context", ""))
            p = doc.add_paragraph()
            r = p.add_run(f"[Visual: {description}")
            r.italic = True
            r.font.size = Pt(10)
            r.font.color.rgb = RGBColor(0x66, 0x66, 0x66)
            if context:
                r2 = p.add_run(f" — {context}")
                r2.italic = True
                r2.font.size = Pt(9)
                r2.font.color.rgb = RGBColor(0x88, 0x88, 0x88)
            p.add_run("]")

    # Footer
    doc.add_paragraph("")
    footer = doc.add_paragraph()
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    fr = footer.add_run("Created with Claw-ED")
    fr.font.size = Pt(8)
    fr.font.color.rgb = RGBColor(0x99, 0x99, 0x99)

    # Save
    if output_dir is None:
        output_dir = Path("clawed_output").resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    safe_title = "".join(c for c in title[:40] if c.isalnum() or c in " _-").strip() or "handout"
    out_path = output_dir / f"{safe_title}_handout.docx"
    doc.save(str(out_path))
    return out_path
