"""Master Content Track — single source-of-truth for all lesson output documents.

All output documents (lesson plan, student packet, slideshow) are compiled as
views of a single ``MasterContent`` object rather than generated by separate LLM
calls.  This eliminates content drift between documents and reduces total token
usage.
"""

from __future__ import annotations

from pydantic import BaseModel, Field, field_validator

from clawed.models import DifferentiationNotes  # reuse — do not duplicate


class VocabularyEntry(BaseModel):
    """A vocabulary term with definition, context sentence, and optional image."""

    term: str
    definition: str
    context_sentence: str
    image_spec: str = ""


class PrimarySource(BaseModel):
    """A primary-source document used in instruction or station work."""

    id: str
    title: str
    source_type: str  # "text_excerpt", "political_cartoon", "map", "data_table", "photograph", "diagram"
    content_text: str
    attribution: str
    image_spec: str = ""
    scaffolding_questions: list[str] = Field(default_factory=list)


class InstructionSection(BaseModel):
    """One section of the direct-instruction sequence."""

    heading: str
    content: str
    teacher_script: str
    key_points: list[str] = Field(default_factory=list)
    image_spec: str = ""


class GuidedNote(BaseModel):
    """A single fill-in-the-blank guided-notes item."""

    prompt: str
    answer: str
    section_ref: str


class StationDocument(BaseModel):
    """A learning-station task tied to a primary source."""

    title: str
    source_ref: str  # id of the referenced PrimarySource
    task: str
    student_directions: str
    teacher_answer_key: str


class StimulusQuestion(BaseModel):
    """An assessment question anchored to a stimulus (text, image, data, etc.).

    Every question *must* have a non-empty stimulus — this is a hard pedagogical
    requirement enforced at validation time.
    """

    stimulus: str
    stimulus_type: str  # "text_excerpt", "image", "data", "map", "diagram", "scenario"
    stimulus_image_spec: str = ""
    question: str
    answer: str
    cognitive_level: str = ""  # "recall", "application", "analysis"

    @field_validator("stimulus", mode="before")
    @classmethod
    def _require_stimulus(cls, v: object) -> object:
        if isinstance(v, str) and not v.strip():
            raise ValueError(
                "stimulus must not be empty — every question needs a pedagogical anchor"
            )
        return v


class DoNow(BaseModel):
    """The lesson-opening Do Now activity."""

    stimulus: str
    stimulus_type: str
    questions: list[str]
    answers: list[str]


class IndependentWork(BaseModel):
    """Structured independent-practice task."""

    task: str
    rubric_snippet: str = ""
    exemplar: str = ""


class MasterContent(BaseModel):
    """Single source-of-truth for an entire lesson.

    All output documents are compiled as views of this object.  Field names
    intentionally mirror the sections of a typical NYC/state lesson plan.
    """

    title: str
    subject: str
    grade_level: str
    topic: str
    standards: list[str] = Field(default_factory=list)
    objective: str
    duration_minutes: int = 45

    vocabulary: list[VocabularyEntry] = Field(default_factory=list)
    primary_sources: list[PrimarySource] = Field(default_factory=list)
    do_now: DoNow
    direct_instruction: list[InstructionSection]
    guided_notes: list[GuidedNote]
    stations: list[StationDocument] = Field(default_factory=list)
    independent_work: IndependentWork | None = None
    exit_ticket: list[StimulusQuestion]
    differentiation: DifferentiationNotes
    homework: str | None = None
    materials_needed: list[str] = Field(default_factory=list)

    # ── backwards-compat bridge ────────────────────────────────────────────

    def to_daily_lesson(self) -> "DailyLesson":  # noqa: F821 — resolved at runtime
        """Return a legacy ``DailyLesson`` compiled from this MasterContent.

        Allows existing code that expects ``DailyLesson`` objects to continue
        working without modification while the rest of the codebase migrates to
        the Master Content Track.
        """
        from clawed.models import DailyLesson, ExitTicketQuestion

        do_now_text = self.do_now.stimulus
        if self.do_now.questions:
            do_now_text += "\n\n" + "\n".join(
                f"Q: {q}" for q in self.do_now.questions
            )

        direct_instruction_text = "\n\n".join(
            f"## {s.heading}\n{s.content}" for s in self.direct_instruction
        )

        guided_practice_text = "\n".join(
            f"- {n.prompt} (Answer: {n.answer})" for n in self.guided_notes
        )

        exit_ticket_items = [
            ExitTicketQuestion(
                question=f"{q.stimulus}\n\n{q.question}",
                expected_response=q.answer,
            )
            for q in self.exit_ticket
        ]

        return DailyLesson(
            title=self.title,
            lesson_number=1,
            objective=self.objective,
            standards=self.standards,
            do_now=do_now_text,
            direct_instruction=direct_instruction_text,
            guided_practice=guided_practice_text,
            independent_work=self.independent_work.task if self.independent_work else "",
            exit_ticket=exit_ticket_items,
            homework=self.homework or "",
            differentiation=self.differentiation,
            materials_needed=self.materials_needed,
        )
