"""Export, share, demo, import, and landing page commands."""

from __future__ import annotations

import json
import platform
import re
import subprocess
import webbrowser
from pathlib import Path
from typing import Optional
from urllib.parse import urlparse

import typer
from rich.panel import Panel
from rich.table import Table

from clawed.commands._helpers import console
from clawed.database import Database

export_app = typer.Typer()


# ── Share HTML helpers ───────────────────────────────────────────────────


def _esc(text: str) -> str:
    """Escape HTML special characters."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def _lesson_to_html(data: dict) -> str:
    """Convert a lesson JSON dict to a self-contained HTML page."""
    title = data.get("title", "Lesson Plan")
    objective = data.get("objective", "")
    do_now = data.get("do_now", "")
    direct_instruction = data.get("direct_instruction", "")
    guided_practice = data.get("guided_practice", "")
    independent_work = data.get("independent_work", "")
    homework = data.get("homework", "")
    standards = data.get("standards", [])
    materials_needed = data.get("materials_needed", [])
    lesson_number = data.get("lesson_number", "")

    exit_tickets = data.get("exit_ticket", [])
    exit_html = ""
    if exit_tickets:
        for et in exit_tickets:
            q = (
                et.get("question", "")
                if isinstance(et, dict)
                else str(et)
            )
            exit_html += f"<li>{_esc(q)}</li>"
        exit_html = f"<ol>{exit_html}</ol>"

    diff = data.get("differentiation", {})
    diff_html = ""
    if isinstance(diff, dict):
        for key, val in diff.items():
            if val:
                label = key.replace("_", " ").title()
                diff_html += (
                    f"<p><strong>{_esc(label)}:</strong>"
                    f" {_esc(str(val))}</p>"
                )

    standards_html = ""
    if standards:
        standards_html = ", ".join(_esc(s) for s in standards)

    materials_html = ""
    if materials_needed:
        materials_html = ", ".join(_esc(m) for m in materials_needed)

    def _section(heading: str, body: str) -> str:
        if not body:
            return ""
        return (
            f'<div class="section"><h3>{heading}</h3>'
            f"<p>{_esc(body)}</p></div>"
        )

    sections = [
        _section("Objective (SWBAT)", objective),
        _section("Do-Now", do_now),
        _section("Direct Instruction", direct_instruction),
        _section("Guided Practice", guided_practice),
        _section("Independent Work", independent_work),
    ]
    if exit_html:
        sections.append(
            f'<div class="section"><h3>Exit Ticket</h3>{exit_html}</div>'
        )
    if homework:
        sections.append(_section("Homework", homework))
    if diff_html:
        sections.append(
            f'<div class="section">'
            f"<h3>Differentiation</h3>{diff_html}</div>"
        )

    num_label = f"Lesson {lesson_number}: " if lesson_number else ""

    standards_line = (
        f"<strong>Standards:</strong> {standards_html}<br>"
        if standards_html
        else ""
    )
    materials_line = (
        f"<strong>Materials:</strong> {materials_html}"
        if materials_html
        else ""
    )

    return f"""\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{_esc(title)}</title>
<style>
  *, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    line-height: 1.6; color: #1a1a2e; background: #fff; max-width: 800px;
    margin: 0 auto; padding: 2rem 1.5rem;
  }}
  h1 {{ font-size: 1.8rem; margin-bottom: .25rem; color: #0f3460; }}
  .meta {{ color: #555; margin-bottom: 1.5rem; font-size: .95rem; }}
  .section {{ margin-bottom: 1.25rem; }}
  h3 {{
    font-size: 1.1rem; color: #16213e; margin-bottom: .3rem;
    border-left: 3px solid #0f3460; padding-left: .6rem;
  }}
  p {{ margin-bottom: .5rem; }}
  ol {{ padding-left: 1.3rem; margin-bottom: .5rem; }}
  li {{ margin-bottom: .25rem; }}
  .footer {{
    margin-top: 2rem; padding-top: 1rem;
    border-top: 1px solid #ddd; color: #888; font-size: .85rem;
  }}
</style>
</head>
<body>
<h1>{_esc(num_label + title)}</h1>
<p class="meta">
  {standards_line}
  {materials_line}
</p>
{"".join(sections)}
<div class="footer">\
Generated by EDUagent &mdash; \
<a href="https://github.com/SirhanMacx/eduagent">\
github.com/SirhanMacx/eduagent</a></div>
</body>
</html>
"""


# ── Demo HTML constant ───────────────────────────────────────────────────

_DEMO_HTML = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>EDUagent Demo</title>
<style>
  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    line-height: 1.6; color: #1a1a2e; background: #fff; max-width: 860px;
    margin: 0 auto; padding: 2rem 1.5rem;
  }
  h1 { font-size: 2rem; margin-bottom: .25rem; }
  .subtitle { color: #555; margin-bottom: 2rem; font-size: 1.1rem; }
  h2 {
    font-size: 1.35rem; margin: 2rem 0 .75rem; color: #16213e;
    border-bottom: 2px solid #0f3460; padding-bottom: .3rem;
  }
  table { width: 100%%; border-collapse: collapse; margin-bottom: 1.5rem; }
  th, td { text-align: left; padding: .65rem .85rem; border: 1px solid #ddd; }
  th { background: #0f3460; color: #fff; font-weight: 600; }
  tr:nth-child(even) { background: #f8f9fa; }
  td:first-child { font-weight: 600; white-space: nowrap; width: 200px; }
  .get-started {
    background: #f0f4ff; border: 1px solid #0f3460; border-radius: 8px;
    padding: 1.5rem; margin-top: 2.5rem;
  }
  .get-started h2 { border: none; margin-top: 0; padding-bottom: 0; }
  .get-started ol { padding-left: 1.3rem; }
  .get-started li { margin-bottom: .4rem; }
  code {
    background: #eef; padding: .15rem .4rem; border-radius: 3px;
    font-family: "SF Mono", "Fira Code", "Cascadia Code", monospace;
    font-size: .92em;
  }
  a { color: #0f3460; }
  .badge-row { display: flex; gap: .5rem; margin-bottom: 1.5rem; flex-wrap: wrap; }
  .badge {
    display: inline-block; padding: .2rem .65rem; border-radius: 4px;
    font-size: .8rem; font-weight: 600; color: #fff;
  }
  .badge-blue { background: #0f3460; }
  .badge-green { background: #2e7d32; }
  .badge-orange { background: #e65100; }
</style>
</head>
<body>
<h1>EDUagent Demo</h1>
<p class="subtitle">\
No API key needed &mdash; example output for \
8th Grade Science / Photosynthesis / 2 weeks</p>
<div class="badge-row">
  <span class="badge badge-blue">Python 3.10+</span>
  <span class="badge badge-green">MIT License</span>
  <span class="badge badge-orange">Works with Ollama</span>
</div>

<h2>Sample Unit Plan</h2>
<table>
  <tr><th>Field</th><th>Value</th></tr>
  <tr><td>Title</td><td>Life From Light: Understanding Photosynthesis</td></tr>
  <tr><td>Grade</td><td>8th Grade Science</td></tr>
  <tr><td>Duration</td><td>2 weeks / 10 lessons</td></tr>
  <tr><td>Essential Questions</td><td>\
How do plants convert light into food?<br>\
Why does photosynthesis matter for all life on Earth?<br>\
How do plants and animals depend on each other?</td></tr>
  <tr><td>Enduring Understandings</td><td>\
Energy flows through ecosystems starting with photosynthesis.<br>\
Matter and energy transformations obey conservation laws.</td></tr>
  <tr><td>Lesson Sequence</td><td>\
L1: What is Photosynthesis? The Big Picture<br>\
L2: Light Energy and Chlorophyll<br>\
L3: The Light-Dependent Reactions<br>\
L4: The Calvin Cycle<br>\
L5: Lab &mdash; Leaf Disk Assay<br>\
L6&ndash;10: Factors, Applications &amp; Assessment</td></tr>
</table>

<h2>Sample Lesson Plan &mdash; Lesson 1</h2>
<table>
  <tr><th>Component</th><th>Content</th></tr>
  <tr><td>Objective (SWBAT)</td><td>\
Students will be able to write the overall equation for photosynthesis \
and explain what enters and exits the leaf.</td></tr>
  <tr><td>Do-Now (5 min)</td><td>\
Look at the photo on the board. Where does a plant get its food? \
Write your hypothesis in 2 sentences.</td></tr>
  <tr><td>Direct Instruction (20 min)</td><td>\
Walk through the big-picture equation: sunlight = power, \
CO&#8322; + H&#8322;O = raw materials, glucose = product. \
Use the chloroplast diagram on p.&nbsp;34.</td></tr>
  <tr><td>Guided Practice (15 min)</td><td>\
Leaf observation: each pair gets a leaf, hand lens, and recording sheet. \
Students sketch the leaf structure and label where photosynthesis occurs.</td></tr>
  <tr><td>Exit Ticket (5 min)</td><td>\
1. Write the word equation for photosynthesis.<br>\
2. Name ONE thing a plant needs from the environment.<br>\
3. Name ONE thing a plant releases.</td></tr>
  <tr><td>Differentiation</td><td>\
Struggling: sentence frames for exit ticket.<br>\
Advanced: research C4 vs C3 photosynthesis.</td></tr>
</table>

<div class="get-started">
  <h2>Get Started</h2>
  <ol>
    <li><code>pip install eduagent</code></li>
    <li><code>eduagent config set-model ollama</code> &nbsp;(free, local)</li>
    <li><code>eduagent ingest ~/your-lesson-plans/</code></li>
    <li><code>\
eduagent full "Photosynthesis" --grade 8 --subject science --weeks 2\
</code></li>
  </ol>
  <p style="margin-top:1rem;">GitHub: \
<a href="https://github.com/SirhanMacx/eduagent">\
github.com/SirhanMacx/eduagent</a></p>
</div>
</body>
</html>
"""


# ── Export command ─────────────────────────────────────────────────────


@export_app.command("export")
def export_cmd(
    lesson_file: str = typer.Option(
        ..., "--lesson-file", "-l", help="Path to lesson JSON"
    ),
    fmt: str = typer.Option(
        "classroom",
        "--format",
        "-f",
        help="Export format: classroom",
    ),
):
    """Export a lesson plan (e.g., to Google Classroom JSON)."""
    path = Path(lesson_file).expanduser().resolve()
    if not path.exists():
        console.print(f"[red]File not found:[/red] {path}")
        raise typer.Exit(1)

    data = json.loads(path.read_text(encoding="utf-8"))

    if fmt == "classroom":
        description_parts = [data.get("objective", "")]
        if data.get("standards"):
            description_parts.append(
                f"Standards: {', '.join(data['standards'])}"
            )
        if data.get("homework"):
            description_parts.append(f"Homework: {data['homework']}")

        coursework = {
            "title": data.get("title", "Lesson"),
            "description": "\n\n".join(description_parts),
            "materials": [],
            "maxPoints": 100,
            "workType": "ASSIGNMENT",
            "state": "DRAFT",
            "submissionModificationMode": "MODIFIABLE_UNTIL_TURNED_IN",
        }

        output = json.dumps(coursework, indent=2)
        console.print(
            Panel(output, title="Google Classroom CourseWork JSON")
        )

        out_path = path.with_suffix(".classroom.json")
        out_path.write_text(output, encoding="utf-8")
        console.print(f"[green]Saved:[/green] {out_path}")
    else:
        console.print(f"[red]Unsupported format: {fmt}[/red]")
        raise typer.Exit(1)


# ── Share command ────────────────────────────────────────────────────


@export_app.command()
def share(
    lesson_file: Optional[str] = typer.Option(
        None,
        "--lesson-file",
        "-l",
        help="Path to a saved lesson JSON file",
    ),
    lesson_id: Optional[str] = typer.Option(
        None, "--lesson-id", help="Lesson ID from the database"
    ),
    host: str = typer.Option(
        "http://localhost:8000",
        "--host",
        help="Server URL for shareable link",
    ),
    embed: bool = typer.Option(
        False,
        "--embed",
        help="Print an HTML embed snippet for the student chat widget",
    ),
    copy: bool = typer.Option(
        False,
        "--copy",
        help="Copy the share URL to the clipboard (macOS)",
    ),
):
    """Generate a shareable link or HTML file from a lesson.

    Use --lesson-id to get a shareable URL (requires the web server),
    or --lesson-file to generate a self-contained HTML file.
    """
    if lesson_id:
        db = Database()
        lesson = db.get_lesson(lesson_id)
        if not lesson:
            console.print(f"[red]Lesson not found:[/red] {lesson_id}")
            db.close()
            raise typer.Exit(1)
        token = lesson.get("share_token")
        if not token:
            console.print(
                "[red]No share token available for this lesson.[/red]"
            )
            db.close()
            raise typer.Exit(1)
        share_url = f"{host}/shared/{token}"

        # Build Rich panel content
        panel_lines = [f"[bold green]Share URL:[/bold green] {share_url}"]

        embed_snippet = (
            f'<script src="{host}/widget.js"'
            f' data-token="{token}" async></script>'
        )
        if embed:
            panel_lines.append(
                f"\n[bold cyan]Embed snippet:[/bold cyan]\n{embed_snippet}"
            )

        panel_lines.append(
            "\n[dim]Hint: Anyone with this link can view the lesson.[/dim]"
        )

        console.print(
            Panel(
                "\n".join(panel_lines),
                title="Lesson Share",
                border_style="green",
            )
        )

        if copy and platform.system() == "Darwin":
            try:
                subprocess.run(
                    ["pbcopy"],
                    input=share_url.encode(),
                    check=True,
                )
                console.print("[green]URL copied to clipboard.[/green]")
            except (FileNotFoundError, subprocess.CalledProcessError):
                pass

        db.close()
        return

    if not lesson_file:
        console.print(
            "[red]Provide --lesson-file or --lesson-id.[/red]"
        )
        raise typer.Exit(1)

    path = Path(lesson_file).expanduser().resolve()
    if not path.exists():
        console.print(f"[red]File not found:[/red] {path}")
        raise typer.Exit(1)

    data = json.loads(path.read_text(encoding="utf-8"))
    title = data.get("title", "lesson")
    safe_title = re.sub(r"[^a-zA-Z0-9_-]", "_", title).strip("_")[:80]

    out_dir = Path("eduagent_output/shared").resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    html_path = out_dir / f"lesson_{safe_title}.html"

    html_path.write_text(_lesson_to_html(data), encoding="utf-8")
    console.print(f"[green]Shareable lesson saved:[/green] {html_path}")


# ── Import command ──────────────────────────────────────────────────────


def _extract_token(value: str) -> str:
    """Extract a share token from a URL or return the value as-is."""
    parsed = urlparse(value)
    if parsed.scheme and parsed.netloc:
        # It's a URL — take the last path segment as the token
        return parsed.path.rstrip("/").rsplit("/", 1)[-1]
    return value


@export_app.command("import")
def import_lesson(
    source: str = typer.Argument(
        ..., help="Share URL or token to import"
    ),
    server: str = typer.Option(
        "http://localhost:8000",
        "--server",
        help="Server URL to fetch the lesson from",
    ),
):
    """Import a shared lesson by URL or token."""
    import httpx

    token = _extract_token(source)
    if not token:
        console.print("[red]Could not extract token from input.[/red]")
        raise typer.Exit(1)

    # Build fetch URL: if the source was a full URL, use its host
    parsed = urlparse(source)
    if parsed.scheme and parsed.netloc:
        fetch_url = f"{parsed.scheme}://{parsed.netloc}/share/{token}"
    else:
        fetch_url = f"{server.rstrip('/')}/share/{token}"

    try:
        resp = httpx.get(fetch_url, timeout=15)
    except httpx.HTTPError as exc:
        console.print(f"[red]Network error:[/red] {exc}")
        raise typer.Exit(1)

    if resp.status_code == 404:
        console.print(
            f"[red]Lesson not found for token:[/red] {token}"
        )
        raise typer.Exit(1)

    if resp.status_code != 200:
        console.print(
            f"[red]Server returned status {resp.status_code}[/red]"
        )
        raise typer.Exit(1)

    try:
        data = resp.json()
    except (json.JSONDecodeError, ValueError):
        console.print("[red]Invalid JSON response from server.[/red]")
        raise typer.Exit(1)

    lesson_data = data.get("lesson", data)
    original_title = data.get("title", lesson_data.get("title", "Untitled"))
    title = f"[Imported] {original_title}"

    db = Database()
    new_id = db.insert_lesson(
        unit_id="imported",
        lesson_number=0,
        title=title,
        lesson_json=json.dumps(lesson_data),
        materials_json=None,
    )
    db.close()

    console.print(f"[green]✓ Imported lesson {new_id}: {title}[/green]")


# ── Demo command ─────────────────────────────────────────────────────────


@export_app.command()
def demo(
    web: bool = typer.Option(
        False,
        "--web",
        help="Generate an HTML demo page and open it in your browser",
    ),
):
    """Show a sample output without needing an API key or any files.

    Prints a realistic example unit plan and lesson plan to demonstrate
    what EDUagent generates. No setup required.
    """
    if web:
        out_dir = Path("~/eduagent_output").expanduser().resolve()
        out_dir.mkdir(parents=True, exist_ok=True)
        html_path = out_dir / "demo.html"
        html_path.write_text(_DEMO_HTML, encoding="utf-8")
        console.print(f"[green]Demo HTML saved:[/green] {html_path}")
        webbrowser.open(html_path.as_uri())
        return

    from clawed.demo import load_demo

    unit_data = load_demo("unit_plan")
    lesson_data = load_demo("lesson_social_studies_g8")

    console.print(
        Panel(
            "[bold green]EDUagent Demo[/bold green]"
            " — no API key needed\n"
            f"This is example output for:"
            f" Grade {unit_data.get('grade_level', '8')}"
            f" {unit_data.get('subject', 'Social Studies')}"
            f" / {unit_data.get('topic', '')}"
            f" / {unit_data.get('duration_weeks', 2)} weeks",
            title="EDUagent",
            border_style="green",
        )
    )

    # Unit plan from packaged demo JSON
    unit_table = Table(
        title="Sample Unit Plan",
        show_header=True,
        header_style="bold cyan",
    )
    unit_table.add_column("Field", style="bold")
    unit_table.add_column("Value")
    unit_table.add_row("Title", unit_data.get("title", ""))
    unit_table.add_row(
        "Grade",
        f"Grade {unit_data.get('grade_level', '')} {unit_data.get('subject', '')}",
    )
    unit_table.add_row(
        "Duration",
        f"{unit_data.get('duration_weeks', '')} weeks"
        f" / {len(unit_data.get('daily_lessons', []))} lessons",
    )
    unit_table.add_row(
        "Essential Questions",
        "\n".join(unit_data.get("essential_questions", [])),
    )
    unit_table.add_row(
        "Enduring Understandings",
        "\n".join(unit_data.get("enduring_understandings", [])),
    )
    lessons_summary = "\n".join(
        f"L{lesson['lesson_number']}: {lesson['topic']}"
        for lesson in unit_data.get("daily_lessons", [])
    )
    unit_table.add_row("Lesson Sequence", lessons_summary)
    console.print(unit_table)

    console.print()

    # Lesson plan from packaged demo JSON
    lesson_table = Table(
        title=f"Sample Lesson Plan — {lesson_data.get('title', 'Lesson 1')}",
        show_header=True,
        header_style="bold magenta",
    )
    lesson_table.add_column("Component", style="bold")
    lesson_table.add_column("Content", max_width=70)
    lesson_table.add_row(
        "Objective (SWBAT)", lesson_data.get("objective", "")
    )
    lesson_table.add_row(
        "Do-Now", lesson_data.get("do_now", "")
    )
    lesson_table.add_row(
        "Direct Instruction", lesson_data.get("direct_instruction", "")
    )
    lesson_table.add_row(
        "Guided Practice", lesson_data.get("guided_practice", "")
    )
    exit_tickets = lesson_data.get("exit_ticket", [])
    if isinstance(exit_tickets, list):
        et_text = "\n".join(
            f"{i + 1}. {t['question']}" if isinstance(t, dict) else str(t)
            for i, t in enumerate(exit_tickets)
        )
    else:
        et_text = str(exit_tickets)
    lesson_table.add_row("Exit Ticket", et_text)
    diff = lesson_data.get("differentiation", {})
    if isinstance(diff, dict):
        diff_text = "\n".join(
            f"{k.title()}: {', '.join(v) if isinstance(v, list) else v}"
            for k, v in diff.items()
        )
    else:
        diff_text = str(diff)
    lesson_table.add_row("Differentiation", diff_text)
    console.print(lesson_table)

    console.print()
    console.print(
        Panel(
            "[bold]To generate real content from your own"
            " materials:[/bold]\n\n"
            "  1. [cyan]pip install eduagent[/cyan]\n"
            "  2. [cyan]eduagent config set-model ollama[/cyan]"
            "  (free, local)\n"
            "  3. [cyan]eduagent ingest"
            " ~/your-lesson-plans/[/cyan]\n"
            '  4. [cyan]eduagent full "Photosynthesis"'
            " --grade 8 --subject science --weeks 2[/cyan]\n\n"
            "GitHub: [link]https://github.com/SirhanMacx/"
            "eduagent[/link]",
            title="Get Started",
            border_style="cyan",
        )
    )


# ── Landing page commands ────────────────────────────────────────────


@export_app.command(name="generate-landing")
def generate_landing(
    output: str = typer.Option(
        "./eduagent_output/landing",
        "--output",
        "-o",
        help="Output directory",
    ),
    open_browser: bool = typer.Option(
        True,
        "--open/--no-open",
        help="Open in browser after generating",
    ),
):
    """Generate the EDUagent landing page (self-contained HTML)."""
    landing_src = Path(__file__).parent.parent / "landing" / "index.html"
    if not landing_src.exists():
        console.print("[red]Landing page template not found.[/red]")
        raise typer.Exit(1)

    out_dir = Path(output).expanduser().resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    dest = out_dir / "index.html"
    dest.write_text(landing_src.read_text(encoding="utf-8"), encoding="utf-8")

    console.print(f"[green]Landing page generated:[/green] {dest}")
    if open_browser:
        webbrowser.open(dest.as_uri())


@export_app.command()
def landing(
    serve_page: bool = typer.Option(
        False,
        "--serve",
        help="Serve the landing page on port 8080",
    ),
    port: int = typer.Option(
        8080, "--port", "-p", help="Port for serving"
    ),
):
    """View or serve the EDUagent landing page."""
    import functools
    import http.server

    landing_dir = Path(__file__).parent.parent / "landing"
    landing_file = landing_dir / "index.html"
    if not landing_file.exists():
        console.print("[red]Landing page not found.[/red]")
        raise typer.Exit(1)

    if serve_page:
        handler = functools.partial(
            http.server.SimpleHTTPRequestHandler,
            directory=str(landing_dir),
        )
        with http.server.HTTPServer(("0.0.0.0", port), handler) as server:
            console.print(
                f"[green]Landing page serving at[/green]"
                f" http://localhost:{port}"
            )
            console.print("[dim]Press Ctrl+C to stop[/dim]")
            try:
                server.serve_forever()
            except KeyboardInterrupt:
                console.print("\n[yellow]Stopped.[/yellow]")
    else:
        webbrowser.open(landing_file.as_uri())
